[package]
name = "codec-fixtures"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
hex = "0.4.3"
ipld-core = { version = "0.4.1", features = ["serde"] }
ipld-dagpb = "*"
multihash-codetable = { version = "0.1.2", features = ["sha2"] }
serde_ipld_dagcbor = "*"
serde_ipld_dagjson = "*"
thiserror = "1.0.58"

[patch.crates-io]
ipld-core = { git = "https://github.com/ipld/rust-ipld-core" }
ipld-dagpb = { git = "https://github.com/ipld/rust-ipld-dagpb" }
serde_ipld_dagcbor = { git = "https://github.com/ipld/serde_ipld_dagcbor" }
serde_ipld_dagjson = { git = "https://github.com/ipld/serde_ipld_dagjson" }
