on:
  push:
  pull_request:
  schedule:
    - cron:  '0 23 * * 2,4,6'

name: Test against latest libraries

jobs:
  node:
    name: Node.js
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x, lts/*]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: js
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install latest version of dependencies
        run: npm install $(node -pe 'Object.keys(require("./package.json").dependencies).map((d) => `${d}@latest`).join(" ")');
      - name: Node.js information
        run: |
          node -v
          npm -v
          npm ls
      - name: Run tests
        run: npm test
  go:
    name: go
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x]
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v2
      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install latest version of dependencies
        run: |
          go get github.com/ipld/go-ipld-prime@master
          go get -u -d
      - name: Go information
        run: |
          go version
          go env
          cat go.mod
      - name: Run tests
        run: go test -v ./...
